/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3U.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3U.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Stardust3UsimpleCAD001.geometry} material={materials['Opaque(202,209,238).004']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_1.geometry} material={materials['Opaque(160,160,160).001']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_2.geometry} material={materials['Opaque(255,108,47)']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_3.geometry} material={materials['Opaque(133,237,168).004']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_4.geometry} material={materials['Opaque(168,168,168).003']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_5.geometry} material={materials['Opaque(255,206,117).003']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_6.geometry} material={materials['Opaque(255,255,255).003']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_7.geometry} material={materials['Opaque(191,191,191).003']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_8.geometry} material={materials['Opaque(66,66,66).004']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_9.geometry} material={materials['Opaque(236,236,236).003']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_10.geometry} material={materials['Opaque(68,119,102).001']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_11.geometry} material={materials['Opaque(224,242,255).001']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_12.geometry} material={materials['Opaque(237,206,195).001']} />
        <mesh geometry={nodes.Stardust3UsimpleCAD001_13.geometry} material={materials['Opaque(218,89,89).001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3U.glb')
